### ISSUE TITLE
Elasticsearch error!

### ISSUE THREAD

**Issue by romablog** [RaananW/express.js-elasticsearch-autocomplete-demo#1]
Elasticsearch ERROR: 2016-02-13T14:29:11Z
  Error: Request error, retrying -- connect ECONNREFUSED 127.0.0.1:9200
i have an error when i start it project may be i need to install something to make it works! 
the same problem when i install the last elasticsearch. 
please help if you can!

**Comment by RaananW** [comment]
Hi,
I am not sure what system you are using, but for this demo all you need to do is to download elastic search and run it. there is no installation involved. 
If you want to describe what you did in order to use elasticsearch, I might be able to help some more.

**Comment by romablog** [comment]
thanks) it's was a my problem) your example very good and helpful)
