### ISSUE TITLE
   No living connections !  Unhandled rejection Error: No Living connections

### ISSUE THREAD

**Issue by matt212** [RaananW/express.js-elasticsearch-autocomplete-demo#2]
Hi, 

When I am trying to run your codebase i get error attached in screenshot 
![issues](https://cloud.githubusercontent.com/assets/1698139/14814679/f3e7a152-0bc4-11e6-86c2-96b4ac5f5431.png)
Could you please suggest some walkthrough in order to run this codebase 
I am using windows 8.1  operating system

**Comment by RaananW** [comment]
This means that the elasticsearch server is not running or is unreachable for some reason.

Please make sure elasticsearch is running correctly on your system, and check the connection to 127.0.0.1:9200 (a simple http request will suffice, just check the server is accepting requests).

Not a problem with the code, more a problem with the local setup.

**Comment by matt212** [comment]
I diagnosed the problem with my java version upgrading now to 1.7 hopes it works !
