### ISSUE TITLE
InvalidTypeNameException[mapping type name [_mapping] can't start with '_']

### ISSUE THREAD

**Issue by antkim003** [RaananW/express.js-elasticsearch-autocomplete-demo#3]
Hi when I run npm start I get this error. 

InvalidTypeNameException[mapping type name [_mapping] can't start with '_']

Do you have any insight?

**Comment by RaananW** [comment]
Hi!
I wonder what that is...
Seems like an internal elasticsearch bug, might I say, as I never set this mapping myself. 
What versions are you using (plugin, elasticsearch)?

**Comment by RaananW** [comment]
Closing down, please open if you still need help.
